// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPve_8wZHADdfPcd3KVhTdTz2sS4AbnDA',
    appId: '1:974321642019:web:788a36c16d754ede075f96',
    messagingSenderId: '974321642019',
    projectId: 'edumate-tugas2',
    authDomain: 'edumate-tugas2.firebaseapp.com',
    storageBucket: 'edumate-tugas2.firebasestorage.app',
    measurementId: 'G-MG3Z4W5F1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3FnB7brU7Lv-KZViWpuv2yTYmcndA6k',
    appId: '1:974321642019:android:a45b5a2ab298c943075f96',
    messagingSenderId: '974321642019',
    projectId: 'edumate-tugas2',
    storageBucket: 'edumate-tugas2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWq987sKWl7CAi4jEz6OMhV38XZv1QZA',
    appId: '1:974321642019:ios:031f9cc9510eb0ee075f96',
    messagingSenderId: '974321642019',
    projectId: 'edumate-tugas2',
    storageBucket: 'edumate-tugas2.firebasestorage.app',
    iosBundleId: 'com.example.mobileTugas2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPve_8wZHADdfPcd3KVhTdTz2sS4AbnDA',
    appId: '1:974321642019:web:ed536eefb10fb7ce075f96',
    messagingSenderId: '974321642019',
    projectId: 'edumate-tugas2',
    authDomain: 'edumate-tugas2.firebaseapp.com',
    storageBucket: 'edumate-tugas2.firebasestorage.app',
    measurementId: 'G-3YZHFPFMPK',
  );
}
